import { readFileSync, writeFileSync } from 'fs';
import { log, truncate } from './utils.mjs';

const INPUT_FILE = 'out/top10.json';
const OUTPUT_FILE = 'out/top10.md';

/**
 * Format number with K/M suffix
 */
function formatNumber(num) {
  if (!num) return '0';
  if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
  if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
  return num.toString();
}

/**
 * Format datetime to readable string
 */
function formatDatetime(datetime) {
  if (!datetime) return 'Unknown';
  try {
    const date = new Date(datetime);
    return date.toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  } catch (e) {
    return datetime;
  }
}

/**
 * Generate markdown report
 */
function generateMarkdown(data) {
  const lines = [];
  
  // Header
  lines.push('# X Radar Report');
  lines.push(`**Generated:** ${data.runAt}`);
  lines.push('');
  
  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Total candidates:** ${data.selectionStats?.totalCandidates || 0}`);
  lines.push(`- **After dedup:** ${data.selectionStats?.uniqueAfterDedup || 0}`);
  lines.push(`- **Selected:** ${data.top?.length || 0} (pain: ${data.selectionStats?.painSelected || 0}, reach: ${data.selectionStats?.reachSelected || 0})`);
  if (data.selectionStats?.backfilled > 0) {
    lines.push(`- **Backfilled:** ${data.selectionStats.backfilled}`);
  }
  if (data.selectionStats?.warning) {
    lines.push(`- **Warning:** ${data.selectionStats.warning}`);
  }
  lines.push('');
  
  // Tweets
  lines.push('---');
  lines.push('');
  lines.push('## Top Tweets');
  lines.push('');
  
  if (!data.top || data.top.length === 0) {
    lines.push('*No tweets found in this run.*');
  } else {
    for (const tweet of data.top) {
      const groupLabel = tweet.originalGroup === 'kol' ? 'kol/reach' : tweet.group;
      
      lines.push(`### #${tweet.rank} [${groupLabel}] ${tweet.author || 'Unknown'}`);
      lines.push('');
      lines.push(`**Score:** ${tweet.finalScore} (viral: ${tweet.viralityScore}, fit: ${tweet.filoFitScore})`);
      lines.push(`**Engagement:** ${formatNumber(tweet.likes)} likes, ${formatNumber(tweet.retweets)} RTs, ${formatNumber(tweet.replies)} replies`);
      lines.push(`**Posted:** ${formatDatetime(tweet.datetime)}`);
      lines.push(`**Source:** ${tweet.sourceQuery || 'N/A'}`);
      lines.push('');
      lines.push('> ' + (tweet.text || '*No text*').split('\n').join('\n> '));
      lines.push('');
      lines.push(`[View Tweet](${tweet.url})`);
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }
  
  // Footer
  lines.push('*Report generated by X Radar*');
  
  return lines.join('\n');
}

async function main() {
  log('INFO', 'Starting format process');
  
  // Read input data
  const data = JSON.parse(readFileSync(INPUT_FILE, 'utf-8'));
  log('INFO', `Loaded data from ${INPUT_FILE}`, { tweets: data.top?.length });
  
  // Generate markdown
  const markdown = generateMarkdown(data);
  
  // Write output
  writeFileSync(OUTPUT_FILE, markdown);
  log('INFO', `Markdown written to ${OUTPUT_FILE}`);
}

main().catch(err => {
  log('ERROR', 'Format failed', { error: err.message });
  process.exit(1);
});
